//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetReverification
    {
        public string RUniqueID { get; set; }
        public string RAssetNumber { get; set; }
        public string AssetNumber { get; set; }
        public string RAssetDescription { get; set; }
        public string AssetDescription { get; set; }
        public string RL1CatCode { get; set; }
        public string L1CatCode { get; set; }
        public string RL2CatCode { get; set; }
        public string L2CatCode { get; set; }
        public string RL3CatCode { get; set; }
        public string L3CatCode { get; set; }
        public string RL4CatCode { get; set; }
        public string L4CatCode { get; set; }
        public string RL1LocCode { get; set; }
        public string L1LocCode { get; set; }
        public string L1LocName { get; set; }
        public string RL2LocCode { get; set; }
        public string L2LocCode { get; set; }
        public string L2LocName { get; set; }
        public string RL3LocCode { get; set; }
        public string L3LocCode { get; set; }
        public string L3LocName { get; set; }
        public string RL4LocCode { get; set; }
        public string L4LocCode { get; set; }
        public string L4LocName { get; set; }
        public string RL5LocCode { get; set; }
        public string L5LocCode { get; set; }
        public string L5LocName { get; set; }
        public string RITC1 { get; set; }
        public string ITC1 { get; set; }
        public string RITC2 { get; set; }
        public string ITC2 { get; set; }
        public string RITC3 { get; set; }
        public string ITC3 { get; set; }
        public string RLOCCODEASSET { get; set; }
        public string LOCCODEASSET { get; set; }
        public string RROOMTYPECODE { get; set; }
        public string ROOMTYPECODE { get; set; }
        public string RCODELEVEL { get; set; }
        public string CODELEVEL { get; set; }
        public string RStatus { get; set; }
        public string Status { get; set; }
        public string RDisposedOn { get; set; }
        public string DisposedOn { get; set; }
        public string RVerificationStatus { get; set; }
        public string VerificationStatus { get; set; }
        public string RDateOfVerification { get; set; }
        public string DateOfVerification { get; set; }
        public string RCreatedOn { get; set; }
        public string CreatedOn { get; set; }
        public string RDepreciated { get; set; }
        public string Depreciated { get; set; }
        public string RNetBookValue { get; set; }
        public string NetBookValue { get; set; }
        public string RRemarks { get; set; }
        public string CatCode { get; set; }
    
        public virtual AssetLocation AssetLocation { get; set; }
        public virtual L1Category L1Category { get; set; }
        public virtual L2Category L2Category { get; set; }
        public virtual L2Location L2Location { get; set; }
        public virtual L3Category L3Category { get; set; }
        public virtual L3Location L3Location { get; set; }
        public virtual L4Category L4Category { get; set; }
        public virtual L4Location L4Location { get; set; }
        public virtual L5Location L5Location { get; set; }
    }
}
