//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDepreciation1
    {
        public int DepreciationID { get; set; }
        public string UniqueID { get; set; }
        public string ValueDate { get; set; }
        public string BookValue { get; set; }
        public string DepreciationRate { get; set; }
        public Nullable<System.DateTime> DepreciationDate { get; set; }
        public Nullable<int> DepreciationDays { get; set; }
        public string DepreciationAmount { get; set; }
        public string NetBookValue { get; set; }
        public string L1LocCode { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
