//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.AssetPurchases = new HashSet<AssetPurchase>();
            this.DisposalNumbers = new HashSet<DisposalNumber>();
            this.GatePassTransactions = new HashSet<GatePassTransaction>();
        }
    
        public string UniqueID { get; set; }
        public string AssetNumber { get; set; }
        public string L1CatCode { get; set; }
        public string L2CatCode { get; set; }
        public string L3CatCode { get; set; }
        public string L4CatCode { get; set; }
        public string L1LocCode { get; set; }
        public string L2LocCode { get; set; }
        public string L3LocCode { get; set; }
        public string L4LocCode { get; set; }
        public string L5LocCode { get; set; }
        public string AssetDescription { get; set; }
        public string ITC1 { get; set; }
        public string ITC2 { get; set; }
        public string ITC3 { get; set; }
        public string LOCCODEASSET { get; set; }
        public string ROOMTYPECODE { get; set; }
        public string CODELEVEL { get; set; }
        public string Status { get; set; }
        public string DisposedOn { get; set; }
        public string DisposedBy { get; set; }
        public string VerificationStatus { get; set; }
        public string DateOfVerification { get; set; }
        public string CreatedOn { get; set; }
        public string Depreciated { get; set; }
        public string NetBookValue { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string SerialNumber { get; set; }
        public string Size { get; set; }
    
        public virtual AssetLocation AssetLocation { get; set; }
        public virtual L1Category L1Category { get; set; }
        public virtual L2Category L2Category { get; set; }
        public virtual L2Location L2Location { get; set; }
        public virtual L3Category L3Category { get; set; }
        public virtual L3Location L3Location { get; set; }
        public virtual L4Category L4Category { get; set; }
        public virtual L4Location L4Location { get; set; }
        public virtual L5Location L5Location { get; set; }
        public virtual ICollection<AssetPurchase> AssetPurchases { get; set; }
        public virtual ICollection<DisposalNumber> DisposalNumbers { get; set; }
        public virtual ICollection<GatePassTransaction> GatePassTransactions { get; set; }
    }
}
