//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPurchase
    {
        public string AssetPurchase1 { get; set; }
        public string L1LocCode { get; set; }
        public string UniqueID { get; set; }
        public string PurchaseID { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual AssetLocation AssetLocation { get; set; }
        public virtual PurchaseDetail PurchaseDetail { get; set; }
    }
}
