//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTagging
    {
        public decimal TID { get; set; }
        public string AssetNumber { get; set; }
        public string AssetDescription { get; set; }
        public string Status { get; set; }
        public string category_code { get; set; }
        public string group_code { get; set; }
        public string location_code { get; set; }
        public string section_code { get; set; }
        public string room_code { get; set; }
        public string room_type { get; set; }
        public string floor_code { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string UniqueID { get; set; }
        public string location_name { get; set; }
        public string section_name { get; set; }
        public string Room_name { get; set; }
        public string Room_type_name { get; set; }
        public string floor_name { get; set; }
        public string L3CatCode { get; set; }
        public string L4CatCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> ColorType { get; set; }
    }
}
