//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCompany
    {
        public AssetCompany()
        {
            this.AssetLocations = new HashSet<AssetLocation>();
            this.Suppliers = new HashSet<Supplier>();
            this.UserCompanies = new HashSet<UserCompany>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string MultipleDivision { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State_Province { get; set; }
        public string Zip_PostalCode { get; set; }
        public string Country { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public string Logo { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string MachineCreated { get; set; }
        public string AssetDisposal { get; set; }
        public string AssetMovement { get; set; }
        public int CountryID { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual ICollection<AssetLocation> AssetLocations { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<UserCompany> UserCompanies { get; set; }
    }
}
