//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDisposal
    {
        public AssetDisposal()
        {
            this.DisposalNumbers = new HashSet<DisposalNumber>();
            this.DisposalRemarks = new HashSet<DisposalRemark>();
        }
    
        public string DisposalNumber { get; set; }
        public string L1LocCode { get; set; }
        public string DateOfDisposal { get; set; }
        public string DateOfProcessing { get; set; }
        public string DateOfReProcessing { get; set; }
        public string DateOfReview { get; set; }
        public string DateOfVerification { get; set; }
        public string DateOfAgreement { get; set; }
        public string DateOfValidation { get; set; }
        public string DateOfApproval { get; set; }
        public string DateOfApprovalAM { get; set; }
        public string ProcessingRemarks { get; set; }
        public string ReprocessingRemarks { get; set; }
        public string ReviewRemarks { get; set; }
        public string VerificationRemarks { get; set; }
        public string AgreementRemarks { get; set; }
        public string ValidationRemarks { get; set; }
        public string ApprovalRemarks { get; set; }
        public string ApprovalAMRemarks { get; set; }
        public string DeniedReason { get; set; }
        public int ProcessedBy { get; set; }
        public int ReProcessedBy { get; set; }
        public int ReviewedBy { get; set; }
        public int VerifiedBy { get; set; }
        public int AgreedBy { get; set; }
        public int ValidatedBy { get; set; }
        public int ApprovedBy { get; set; }
        public int ApprovedAMBy { get; set; }
        public int DeniedBy { get; set; }
        public string Status { get; set; }
        public string DisposalSaleValue { get; set; }
    
        public virtual AssetLocation AssetLocation { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
        public virtual User User7 { get; set; }
        public virtual User User8 { get; set; }
        public virtual ICollection<DisposalNumber> DisposalNumbers { get; set; }
        public virtual ICollection<DisposalRemark> DisposalRemarks { get; set; }
    }
}
