//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.AssetCompanies = new HashSet<AssetCompany>();
            this.AssetLocations = new HashSet<AssetLocation>();
        }
    
        public int CountryID { get; set; }
        public string SortName { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AssetCompany> AssetCompanies { get; set; }
        public virtual ICollection<AssetLocation> AssetLocations { get; set; }
    }
}
