//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public string iso { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
