//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposalNumber
    {
        public string AssetDisposalCode { get; set; }
        public string UniqueID { get; set; }
        public string DisposalNumber1 { get; set; }
        public string DenialReason { get; set; }
        public string DeniedBy { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual AssetDisposal AssetDisposal { get; set; }
    }
}
