//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposalRemark
    {
        public int ID { get; set; }
        public string DisposalNumber { get; set; }
        public string Date { get; set; }
        public string RemarkLevel { get; set; }
        public string ApprovalRemarks { get; set; }
        public string DeclineRemarks { get; set; }
        public string RemarksBy { get; set; }
    
        public virtual AssetDisposal AssetDisposal { get; set; }
    }
}
