//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public PurchaseDetail()
        {
            this.AssetPurchases = new HashSet<AssetPurchase>();
        }
    
        public string PurchaseID { get; set; }
        public string SupplierID { get; set; }
        public string L1LocCode { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DateofPurchase { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> DateofPO { get; set; }
        public string iso { get; set; }
        public string UnitPrice { get; set; }
        public string InvoiceImage { get; set; }
        public string PurchaseOrderImage { get; set; }
        public string NetbookValue { get; set; }
        public string AssetNumber { get; set; }
    
        public virtual AssetLocation AssetLocation { get; set; }
        public virtual ICollection<AssetPurchase> AssetPurchases { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
