//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.GatePassTransactions = new HashSet<GatePassTransaction>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierTelephone { get; set; }
        public string SupplierEmail { get; set; }
        public Nullable<int> CountryID { get; set; }
        public int CompanyID { get; set; }
    
        public virtual AssetCompany AssetCompany { get; set; }
        public virtual ICollection<GatePassTransaction> GatePassTransactions { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
