//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AssetDisposals = new HashSet<AssetDisposal>();
            this.AssetDisposals1 = new HashSet<AssetDisposal>();
            this.AssetDisposals2 = new HashSet<AssetDisposal>();
            this.AssetDisposals3 = new HashSet<AssetDisposal>();
            this.AssetDisposals4 = new HashSet<AssetDisposal>();
            this.AssetDisposals5 = new HashSet<AssetDisposal>();
            this.AssetDisposals6 = new HashSet<AssetDisposal>();
            this.AssetDisposals7 = new HashSet<AssetDisposal>();
            this.AssetDisposals8 = new HashSet<AssetDisposal>();
            this.GatePassTransactions = new HashSet<GatePassTransaction>();
            this.GatePassTransactions1 = new HashSet<GatePassTransaction>();
            this.GatePassTransactions2 = new HashSet<GatePassTransaction>();
            this.GatePassTransactions3 = new HashSet<GatePassTransaction>();
            this.User_Activity = new HashSet<User_Activity>();
            this.UserCompanies = new HashSet<UserCompany>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Language { get; set; }
        public string Note { get; set; }
        public bool Asset_Category { get; set; }
        public bool Asset_Description { get; set; }
        public bool Asset_Group { get; set; }
        public bool BarcodeID { get; set; }
        public bool Company_Name { get; set; }
        public bool Floor { get; set; }
        public bool Room_No { get; set; }
        public bool Room_Type { get; set; }
        public bool Section_Name { get; set; }
        public bool Site_Name { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string MachineCreated { get; set; }
        public string AssetDisposal { get; set; }
        public string AssetMovement { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AssetDisposal> AssetDisposals { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals1 { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals2 { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals3 { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals4 { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals5 { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals6 { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals7 { get; set; }
        public virtual ICollection<AssetDisposal> AssetDisposals8 { get; set; }
        public virtual ICollection<GatePassTransaction> GatePassTransactions { get; set; }
        public virtual ICollection<GatePassTransaction> GatePassTransactions1 { get; set; }
        public virtual ICollection<GatePassTransaction> GatePassTransactions2 { get; set; }
        public virtual ICollection<GatePassTransaction> GatePassTransactions3 { get; set; }
        public virtual ICollection<User_Activity> User_Activity { get; set; }
        public virtual ICollection<UserCompany> UserCompanies { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
