//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCompany
    {
        public int UserCompanyID { get; set; }
        public int CompanyID { get; set; }
        public string L1LocCode { get; set; }
        public int UserID { get; set; }
    
        public virtual AssetCompany AssetCompany { get; set; }
        public virtual AssetLocation AssetLocation { get; set; }
        public virtual User User { get; set; }
    }
}
